{{- if .Values.config.vpa.enabled}}
apiVersion: "autoscaling.k8s.io/v1beta2"
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "name" . }}-vpa
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "name" . }}
  updatePolicy:
    updateMode: {{ .Values.config.vpa.updatePolicy.updateMode }}
{{- end }}
