kubernetesVersion: 1.13.5
tenantId: fooTenant
subscriptionId: barSub
aadClientId: fooClient
aadClientSecret: barSecret
resourceGroup: foobarGroup
vnetName: name
subnetName: sname
routeTableName: rtname
securityGroupName: sgname
region: location