{{- if .Values.config.typha.enabled }}
# Config is separated in order to allow computing the SHA256 checksum
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: calico-typha-vertical-autoscaler
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
data:
  typha-autoscaler: |-
    {
      "calico-typha": {
        "requests": {
          "cpu": {
            "base": "120m",
            "step": "80m",
            "nodesPerStep": 10,
            "max": "1000m"
          }
        }
      }
    }
{{- end }}
